### PR TITLE
[Demo X] Active thermal control phase 1

### PR DESCRIPTION
**Pull request by siddarth09**
image

So how does it work ? 

Thermal Control System Integration

This update simulates internal and external cooling loop interactions. The CoolantManager node manages internal water loops A and B, increasing temperature over time and publishing loop status. The ExternalLoopA node subscribes to this data, and if the temperature is above threshold, it performs heat exchange using ammonia. After transferring heat, it publishes the updated status back to CoolantManager, which reduces its internal temperature accordingly. Ammonia is automatically requested from the tank, and heater logic is included for cold-soak protection.

### CODE REVIEW

**Comment by siddarth09** [comment]
[working thermal control.webm](https://github.com/user-attachments/assets/d2000918-1abc-4ccd-a735-61b49e6b634c)

Now, when the output from the external loop, that is, if the heat is more than the said threshold, the radiators are turned on! We can visually see the solar array (acting like radiators) rotate to vent the heat off. The hot ammonia is replaced with cold ammonia

**Comment by yuyuqq** [comment]
Thank you for the great work on this PR.

I am currently encountering a build error due to a missing `delivered_volume` field in the `CleanWater` service response. Specifically, the following error appears when building `thermal_control`:
error: ‘space_station_eclss::srv::CleanWater_Response’ has no member named ‘delivered_volume’
This occurs in `coolant.cpp` at the following lines:

```cpp
if (resp->success && resp->delivered_volume > 0.0) {
    double half = resp->delivered_volume / 2.0;
```
The CleanWater service used here seems to expect a field that is defined only in the space_station_os repository. However, since this is a standalone demo repository, it cannot assume access to or alignment with the full space_station_os codebase by default.

To address this, I see a few design options:
Plan 1: Clone a subset of space_station_os into the demo repository
pro: Makes the demo self-contained
con: Risks divergence or version mismatch with upstream

Plan 2: Redefine a minimal CleanWater service locally in the demo
pro: Allows the demo to build independently
con: Breaks interface consistency with space_station_eclss

Plan 3: Declare an explicit dependency on a pinned version of space_station_os
pro: Maintains canonical interface consistency
pro2: Keeps the demo aligned with actual integration use cases
con: Slightly increases setup complexity

I recommend Option 3: explicitly depending on a known-good version of space_station_os that defines the required CleanWater service. This best preserves consistency and makes future integration more robust. I can help update the README or provide a script for pulling the appropriate version, if helpful.

Let me know your thoughts.

**Comment by siddarth09** [comment]
Merging V1 to have a working plugin
